### ISSUE TITLE
dazn doesn't play streams

### ISSUE THREAD

**Issue by BooStars** [JinRonin/plugin.video.dazn#10]
Hi,
im using latest milhouse-update an inputstream.adaptive (2.3.12) but kodi wont't play any stream
`
17:58:40.149 T:140544560053632  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.dazn/?id=7k0so7e4umqk1gkaf1990ctze&params=9r3lqfmu4ktoin74dqrfhpega&mode=play&title=Lakers+%40+Rockets
17:58:40.150 T:140544455915264  NOTICE: Creating InputStream
17:58:40.745 T:140544455915264   ERROR: AddOnLog: InputStream Adaptive: Unable to find license in JSON string
17:58:40.745 T:140544455915264   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
17:58:40.746 T:140544455915264   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
17:58:40.751 T:140544455915264   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.dazn/?id=7k0so7e4umqk1gkaf1990ctze&params=9r3lqfmu4ktoin74dqrfhpega&mode=play&title=Lakers+%40+Rockets]
17:58:40.752 T:140544455915264  NOTICE: CVideoPlayer::OnExit()
17:58:40.766 T:140544560053632  NOTICE: CVideoPlayer::CloseFile()
17:58:40.766 T:140544560053632  NOTICE: VideoPlayer: waiting for threads to exit
17:58:40.767 T:140544560053632  NOTICE: VideoPlayer: finished waiting`

any hints

**Comment by JinRonin** [comment]
Nope, sorry. You seem to fail to retreive the license. Can you turn on debug log and post the full log?

**Comment by BooStars** [comment]
Hi,
thanks for reply.
here is the debug.log
[kodi.log](https://github.com/JinRonin/plugin.video.dazn/files/2687370/kodi.log)

**Comment by JinRonin** [comment]
Sorry i dont know why its failing for you and im not able to reproduce it.
I would suggest you go to my.dazn.com, logout from all devices and try again.
Also make sure not to use any dns or vpn service.

**Comment by BooStars** [comment]
i just logged out from all my devices, but no help, streams won't play with kodi ;-(
any other ideas?

**Comment by BooStars** [comment]
cant' beleve... just updated the milhouse to latest version, restinstalled dazn-addon and it works...
