### ISSUE TITLE
Different directories for Catch Up and Highlights

### ISSUE THREAD

**Issue by Wombat2018** [JinRonin/plugin.video.dazn#12]
Hi,

it would be nice to have different directories for Catch Up and Highlights.
That would solve my widget problem. Then it would be possible to have one directory with highlights as a widget and it would not be necessary to use the context menu to play the highlights.

**Comment by JinRonin** [comment]
Hi,
the addon supports highlights only listing via context menu.
If you find out where the widget information is stored, you can manually change the path to the addon and have highlights listed only.
The path will look like 
`plugin://plugin.video.dazn/?id=CatchUp&mode=rail&params=PageType%3aSport%3bContentType%3aSport%3bContentId%3a289u5typ3vp4ifwh5thalohmq&title=Catch%20up`
There you only have to change from mode=rail to mode=rail_highlights

**Comment by Wombat2018** [comment]
Does not work for me when I change this:

plugin://plugin.video.dazn/?id=CatchUp&amp;params=PageType%3ASport%3BContentType%3ASport%3BContentId%3A289u5typ3vp4ifwh5thalohmq&amp;mode=rail&amp;title=Catch+up+%26+Highlights&amp;reload=

to this

plugin://plugin.video.dazn/?id=CatchUp&amp;params=PageType%3ASport%3BContentType%3ASport%3BContentId%3A289u5typ3vp4ifwh5thalohmq&amp;mode=rail_highlights&amp;title=Catch+up+%26+Highlights&amp;reload=

**Comment by Wombat2018** [comment]
It was a problem with the skin. However, I have solved it.
