### ISSUE TITLE
MMA age pin authorization 

### ISSUE THREAD

**Issue by bobbypin17** [JinRonin/plugin.video.dazn#13]
DAZN Germany has added age pin authorization for MMA.  The DAZN kodi addon isn’t working for mma now. Can anyone update the DAZN addon to enable pin for mma? I know the developer said he has quit development. Can anyone else update it or maybe the developer can update it one more time?

**Comment by JinRonin** [comment]
try adding the following here https://github.com/JinRonin/plugin.video.dazn/blob/f8178e58895f35ef5867569199b094ef9d12a74c/resources/lib/client.py#L78
` self.HEADERS['x-age-verification-pin'] = 'YOURPIN'`

**Comment by bobbypin17** [comment]
Awesome!!! Thank you so much! Can I donate a few bucks to you?

Sent using the mail.com mail app

**Comment by JinRonin** [comment]
https://github.com/JinRonin/plugin.video.dazn/commit/35e801cce1d6ad74d20273ea56e4a797fd8009df

Please test, i would also like to have a debug log (snippet) when you enter a false pin.

**Comment by bobbypin17** [comment]
I added my PIN number  instead of ‘YOURPIN’

**Comment by MRLB** [comment]
after I start a stream I have enter the pin now. Not only for MMA but also for Futbol etc. Would it be possible to to change the setting that for the 'normal' streams I do not enter the pin every time?

**Comment by JinRonin** [comment]
My bad, should be fixed now. Thanks
Can you help me with the debug log? I cant test myself.

**Comment by MRLB** [comment]
False pin:
`2019-04-08 20:26:28.460 T:8480   DEBUG: [plugin.video.dazn] version: 11.3.1.2 country: DE language: de portability: NativeAndPortabilityAvailable
2019-04-08 20:26:28.460 T:8480   DEBUG: [plugin.video.dazn] error: Invalid pin. (10161)
2019-04-08 20:26:28.462 T:8480   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: playback_data() takes exactly 3 arguments (2 given)
                                            Traceback (most recent call last):
                                              File "C:\Users\[User]\AppData\Roaming\Kodi\addons\plugin.video.dazn\addon.py", line 62, in <module>
                                                router(sys.argv[2][1:])
                                              File "C:\Users\[User]\AppData\Roaming\Kodi\addons\plugin.video.dazn\addon.py", line 37, in router
                                                parser.playback(client.playback(id_, plugin.youth_protection_pin(verify_age)))
                                              File "C:\Users\[User]\AppData\Roaming\Kodi\addons\plugin.video.dazn\resources\lib\client.py", line 94, in playback
                                                data = self.playback_data(id_)
                                            TypeError: playback_data() takes exactly 3 arguments (2 given)
                                            -->End of Python script error report<--
`

**Comment by MRLB** [comment]
Thanks for your support :_)

**Comment by JinRonin** [comment]
If everything is ok now, i'll push the update to the kodi repo.
