### ISSUE TITLE
Support for 50fps

### ISSUE THREAD

**Issue by whitesnakeftw** [JinRonin/plugin.video.dazn#2]
I noticed my stream never goes up to 50fps, but stays 25fps. Let me know if there's any way I can provide my stream.mpd privately, if that helps.

**Comment by whitesnakeftw** [comment]
Are my DAZN credentials somewhere in the log and need to censor them?

**Comment by JinRonin** [comment]
Credentials are not being stored by the addon and therefore not being logged

**Comment by JinRonin** [comment]
This is your display resolution (display size) and bandwidth in order to select a stream from the manifest.
Usually live feeds are 720p/50p and archived ones 1080p/25p, so in your case from log its vod with max 1080p/25p. No 50fps available.
Also according to your download speed it will be hard to get 50fps live streams.
If you're not getting any 50fps streams on live events at all, try setting min bandwidth to 4 000 000 in inputstream adaptive. There is a shortcut in dazn addon settings.

**Comment by whitesnakeftw** [comment]
You were right, that content did not have 50fps, but other VOD events do luckily. Anyway I wasn't getting 50fps on any content at all.

So, I wasn't aware of those addon settings otherwise I would have tried them out earlier. I can confirm that with a Manual setting I'm able to choose whatever quality I want and this way I can easily have 720p50, but even setting 4 000 000 doesn't give me 50fps automatically. Not sure about the speed though, I'm on a 100 mbit connection (in that moment I had at least 40 mbit available) so I wouldn't say it's a problem on my end.

Btw, it seems that with the above settings the preferred stream is always the worst (1/9 or 1/10), and I always have to switch manually to 9/9 or 10/10. If it could be the other way around, it would be a good improvement for the next version (but then again, maybe the problem lies within the wrong detection of the download speed, not sure). This said, I think the issue can be closed now.

OT: I tried to forward the output to VLC 4.0.0, and even though the seek bar and times are there I get no video or audio. I guess this is because VLC receives the encrypted input and is not able to resolve it on its own. Is there any simple way to get the stream working on VLC? Thanks.

**Comment by JinRonin** [comment]
My fault, its MB/s instead of mbit/s so your speed is indeed ok.
Play around with the settings or force min bandwidth to 10 000 000.
Playback via vlc is not possible.

**Comment by anthonytex** [comment]
The addon is working well.
It's dazn that mixes 25fps content with 50fps at least here in Italy.
"live" cdns have 50fps i would say always. "vod" cdns instead have sometimes 720p 50fps or 1080p 25fps as best profile.

**Comment by whitesnakeftw** [comment]
A min bandwidth of 10 000 000 with the Auto selection seems to do the trick (but with a Manual selection it defaults to 1/9), so it's all good now!
