### ISSUE TITLE
Live event not working.

### ISSUE THREAD

**Issue by crimarz** [JinRonin/plugin.video.dazn#4]
Hello,
I'd like to report a problem with your plugin.
Some events like Italy "Serie A TIM" SPAL-PARMA cannot start.
When I try to start the live stream I see always a video that say that event is starting at 17.45.
Even if I try to watch at say 17.50 or 18 or 19 I cannot see the live stream.
I had the same problem with "NAPOLI MILAN" event the day before.
Yesterday there was 4 event simultaneously when I had the problem. 3 of 4 was working correctly.
Only this SPAL-PARMA event had this issue.
I knew that other italian users had the same problem.
Please let me know if you know a workaround to fix it.
Many thanks for your work here. :)
Bye,
C.

**Comment by JinRonin** [comment]
Did you try to skip forward?

Anyway, here is a temp release that lets you manually select the cdn.
https://github.com/JinRonin/plugin.video.dazn/archive/v1.2.0-temp.zip
dazn addon settings - video player -> disable compatibilty mode
You will have to enable it everytime you want to change it as it will save the selected cdn.
Note that in most cases you will need the latest kodi 18 release/nightly

**Comment by JinRonin** [comment]
Yes, they require kodi 18 with updated inputstream.adaptive

**Comment by anthonytex** [comment]
Thank you for the confirmation!
