### ISSUE TITLE
fire tv crashes playing live or vod football match

### ISSUE THREAD

**Issue by dontknowcris** [JinRonin/plugin.video.dazn#6]
when I try to watch a football match on demand, the match starts without any problem, but after some minutes there's a buffering and the video freezes. if I try to stop the playback and going back to football matches list, then kodi crashes and goes back to the home of fire tv. and if I try to play again the same vod, the video always freezes at the same point then the previous one
same issue with live events (obviously in this case, the crash moment is different, depending on when I try to play a match)

here are the error logs
[kodilog1.txt](https://github.com/JinRonin/plugin.video.dazn/files/2346295/kodilog1.txt)
[kodilog2.txt](https://github.com/JinRonin/plugin.video.dazn/files/2346296/kodilog2.txt)

**Comment by JinRonin** [comment]
Sorry can't really help here. You will have to wait for peak3d to look at it.

**Comment by dontknowcris** [comment]
Ok man, thanks

**Comment by dontknowcris** [comment]
hey mate, sorry if I bother you so much, but using your eurosport addon with kodi 18, there are no problems such as crashes or video freeze.
so I think the problem is related to your dazn addon and not to inputatream, imho
@JinRonin

**Comment by dontknowcris** [comment]
debug log
https://github.com/peak3d/inputstream.adaptive/files/2348385/debuglog.txt

results of "logcat -d"
https://paste.ubuntu.com/p/6V7bP9SJnw/

**Comment by JinRonin** [comment]
This is definitely not an addon issue. Eurosport is using a different stream format and drm hence why its working for you.
Please listen to the suggestion from peak3d
