### ISSUE TITLE
DAZN no longer streaming content

### ISSUE THREAD

**Issue by michael-UX** [JinRonin/plugin.video.dazn#7]
Hi Jin,

I've been using the your DAZN plugin since before it was included in Kodi and it has been working incredibly well up until about a week ago when it would no longer stream any content. I still get the manifest lists of 'what's on' but nothing will stream.
I'm not at all sure what the issue is but I do know that I can still login and view streaming content on other devices without issue, so I know my DAZN account is good
I've attached a log file. Hopefully I created it correctly and there's some helpful information in there. I looked and noticed an error 'InputStream Adaptive: License update not successful (no keys)' so that might be where the issue is...?? I have no idea.
Any thoughts on how to correct this would be greatly appreciated.

Thank you in advance and also for creating such a great plugin.

michael

Also: I took a quick look in the cdm folder and all the files in there are as recent as this month except for manifest.json - 01/01/2018, ssd_wv.dll - 08/25/2017 and widevinecdm.dll - 02/20/2018
Not sure if any of that helps.

[kodi.log](https://github.com/JinRonin/plugin.video.dazn/files/2376892/kodi.log)

**Comment by JinRonin** [comment]
You will have to update to the latest kodi 18 beta/nightly with inputstream adaptive 2.2.27
Kodi 17 is unfortunately not supported anymore

**Comment by michael-UX** [comment]
That was quick!
That is good to know.
Thank you for your reply and the info.
